### ISSUE TITLE
IDX20807: Unable to retrieve document from: {openid-configuration URL}

### ISSUE THREAD

**Issue by eamreyes** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#621]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [x] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro Steps

1. Following this tutorial [Configure authentication in a sample web app that calls a web API by using Azure AD B2C](https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-sample-web-app-with-api?tabs=visual-studio)
2. Configure App Settings for API and WebApp
3. Login to the Application
4. Click on `Todo List`
5. Wait for Page to load

**Web App configuration**
```
{
  "AzureAdB2C": {
    "Instance": "https://<myb2c>b2c.b2clogin.com",
    "ClientId": "<MyClientId>",
    "Domain": "<myb2c>b2c.onmicrosoft.com",
    "SignedOutCallbackPath": "/signout/B2C_1A_SIGNUP_SIGNIN",
    "SignUpSignInPolicyId": "B2C_1A_SIGNUP_SIGNIN",
    "EditProfilePolicyId": "", 
    "ClientSecret": "<MyClientSecret>"
  },
  "TodoList": {
    "TodoListScope": "https://<myb2c>b2c.onmicrosoft.com/task-api/tasks.read",
    "TodoListBaseAddress": "https://localhost:44332"

  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
}
```

**API Configuration**
```
{
  "AzureAdB2C": {
    "Instance": "https://<myb2c>b2c.b2clogin.com",
    "ClientId": "<MyApiId>",
    "Domain": "<myb2c>.onmicrosoft.com",
    "SignedOutCallbackPath": "/signout/B2C_1A_SIGNUP_SIGNIN",
    "SignUpSignInPolicyId": "B2C_1A_SIGNUP_SIGNIN"
  },
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "https://localhost:44332"
      }
    }
  },
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*"
}

```
**Expected behavior**
Load the TODO List page

**Actual behavior**
Loads exception page

```
System.Net.Http.HttpRequestException: Invalid status code in the HttpResponseMessage: InternalServerError.
   at TodoListClient.Services.TodoListService.GetAsync() in /Users/eddiereyesmbp/src/neudesic/active-directory-aspnetcore-webapp-openidconnect-v2/4-WebApp-your-API/4-2-B2C/Client/Services/TodoListService.cs:line 115
   at TodoListClient.Controllers.TodoListController.Index() in /Users/eddiereyesmbp/src/neudesic/active-directory-aspnetcore-webapp-openidconnect-v2/4-WebApp-your-API/4-2-B2C/Client/Controllers/TodoListController.cs:line 23
   at lambda_method30(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Possible Solution**
The URL generated by the library for my custom profiles `openid-configuration` location does not match the actual location.

**Actual openid location**
 ```
https://<myb2c>b2c.b2clogin.com/<myb2c>b2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_SIGNUP_SIGNIN
```

**Web API internal exception looks at this URL**
```
https://<myb2c>b2c.b2clogin.com/<myb2c>.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration
```

### Web API Internal 404 Error

```
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      Microsoft.IdentityModel Version: 6.23.1.0. Date 09/29/2022 17:42:02. PII logging is ON, do not use in production. See https://aka.ms/IdentityModel/PII for details. 
      IDX20809: Unable to retrieve document from: 'https://<myb2c>b2c.b2clogin.com/<myb2c>.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration'. Status code: 'NotFound'. 
      Response content: 'The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.'.
fail: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX20807: Unable to retrieve document from: 'https://<myb2c>b2c.b2clogin.com/<myb2c>.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
      {
        X-Frame-Options: DENY
        Public: OPTIONS,TRACE,GET,HEAD,POST
        Strict-Transport-Security: max-age=31536000; includeSubDomains
        X-Content-Type-Options: nosniff
        X-XSS-Protection: 1; mode=block
        Date: Thu, 29 Sep 2022 17:42:01 GMT
        Content-Type: text/html
        Allow: OPTIONS
        Allow: TRACE
        Allow: GET
        Allow: HEAD
        Allow: POST
        Content-Length: 103
      }', HttpResponseMessage.Content: 'The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.'.
fail: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      Message: IDX20803: Unable to obtain configuration from: 'https://<myb2c>b2c.b2clogin.com/<myb2c>.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration'., InnerException: IDX20807: Unable to retrieve document from: 'https://<myb2c>b2c.b2clogin.com/<myb2c>.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
      {
        X-Frame-Options: DENY
        Public: OPTIONS,TRACE,GET,HEAD,POST
        Strict-Transport-Security: max-age=31536000; includeSubDomains
        X-Content-Type-Options: nosniff
        X-XSS-Protection: 1; mode=block
        Date: Thu, 29 Sep 2022 17:42:01 GMT
        Content-Type: text/html
        Allow: OPTIONS
        Allow: TRACE
        Allow: GET
        Allow: HEAD
        Allow: POST
        Content-Length: 103
      }', HttpResponseMessage.Content: 'The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.'.. 
fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
      Exception occurred while processing message.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://<myb2c>b2c.b2clogin.com/<myb2c>.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration'.
       ---> System.IO.IOException: IDX20807: Unable to retrieve document from: 'https://<myb2c>b2c.b2clogin.com/<myb2c>.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
      {
        X-Frame-Options: DENY
        Public: OPTIONS,TRACE,GET,HEAD,POST
        Strict-Transport-Security: max-age=31536000; includeSubDomains
        X-Content-Type-Options: nosniff
        X-XSS-Protection: 1; mode=block
        Date: Thu, 29 Sep 2022 17:42:01 GMT
        Content-Type: text/html
        Allow: OPTIONS
        Allow: TRACE
        Allow: GET
        Allow: HEAD
        Allow: POST
        Content-Length: 103
      }', HttpResponseMessage.Content: 'The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.'.
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://<myb2c>b2c.b2clogin.com/<myb2c>.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration'.
       ---> System.IO.IOException: IDX20807: Unable to retrieve document from: 'https://<myb2c>b2c.b2clogin.com/<myb2c>.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
      {
        X-Frame-Options: DENY
        Public: OPTIONS,TRACE,GET,HEAD,POST
        Strict-Transport-Security: max-age=31536000; includeSubDomains
        X-Content-Type-Options: nosniff
        X-XSS-Protection: 1; mode=block
        Date: Thu, 29 Sep 2022 17:42:01 GMT
        Content-Type: text/html
        Allow: OPTIONS
        Allow: TRACE
        Allow: GET
        Allow: HEAD
        Allow: POST
        Content-Length: 103
      }', HttpResponseMessage.Content: 'The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.'.
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:44332/api/todolist - - - 500 - text/plain;+charset=utf-8 1549.0123m
```

### OS and Version
* MacOS Monterrey 12.6
* IDE Rider

### Versions
* ASP.NET Core: Dotnet 6
* Microsoft.Identity.Web: 1.25.e

**Comment by derisen** [comment]
Closing due to inactivity.
