### ISSUE TITLE
AADSTS501461 on 4-1-MyOrg

### ISSUE THREAD

**Issue by WenningQiu** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#728]
I am getting AADSTS501461 on "4-1-MyOrg" when clicking "TodoList" on the client:

![image](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/assets/4291622/826eb3f0-661f-4330-ab5b-9a0b9e34ad57)

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Exception: An error was encountered while handling the remote login.
       ---> MSAL.NetCore.4.42.0.0.MsalServiceException:
        ErrorCode: invalid_request
Microsoft.Identity.Client.MsalServiceException: AADSTS501461: AcceptMappedClaims is only supported for a token audience matching the application GUID or an audience within the tenant's verified domains. Either change the resource identifier, or use an application-specific signing key.
      Trace ID: 2e8c013a-7896-4f83-b0b2-3f4634c94a00
      Correlation ID: 59038132-1e92-4a0d-81f0-298659aae5e9
      Timestamp: 2023-08-25 15:18:33Z
         at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
         at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
         at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2 onBeforePostRequestData)
         at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders, Func`2 onBeforePostRequestHandler)
         at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
         at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
         at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.ConfidentialAuthCodeRequest.ExecuteAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByAuthorizationCodeParameters authorizationCodeParameters, CancellationToken cancellationToken)
         at Microsoft.Identity.Web.TokenAcquisition.AddAccountToCacheFromAuthorizationCodeAsync(AuthorizationCodeReceivedContext context, IEnumerable`1 scopes, String authenticationScheme)
         at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilder.<>c__DisplayClass11_1.<<WebAppCallsWebApiImplementation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RunAuthorizationCodeReceivedEventAsync(OpenIdConnectMessage authorizationResponse, ClaimsPrincipal user, AuthenticationProperties properties, JwtSecurityToken jwt)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
        StatusCode: 400
        ResponseBody: {"error":"invalid_request","error_description":"AADSTS501461: AcceptMappedClaims is only supported for a token audience matching the application GUID or an audience within the tenant's verified domains. Either change the resource identifier, or use an application-specific signing key.\r\nTrace ID: 2e8c013a-7896-4f83-b0b2-3f4634c94a00\r\nCorrelation ID: 59038132-1e92-4a0d-81f0-298659aae5e9\r\nTimestamp: 2023-08-25 15:18:33Z","error_codes":[501461],"timestamp":"2023-08-25 15:18:33Z","trace_id":"2e8c013a-7896-4f83-b0b2-3f4634c94a00","correlation_id":"59038132-1e92-4a0d-81f0-298659aae5e9","claims":"{\"access_token\":{\"capolids\":{\"essential\":true,\"values\":[\"204fdcd3-323c-4607-90a2-554654667d4e\",\"60a82c71-4482-4dd0-bbb8-cbd43bb4bc75\"]}}}"}
        Headers: Cache-Control: no-store, no-cache
      Pragma: no-cache
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      X-Content-Type-Options: nosniff
      P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
      client-request-id: 59038132-1e92-4a0d-81f0-298659aae5e9
      x-ms-request-id: 2e8c013a-7896-4f83-b0b2-3f4634c94a00
      x-ms-ests-server: 2.1.16150.3 - NCUS ProdSlices
      x-ms-clitelem: 1,501461,0,,
      X-XSS-Protection: 0
      Set-Cookie: fpc=AqSuuoSF02RJgwvVcl15L3MVXd2aAQAAAEi9etwOAAAA; expires=Sun, 24-Sep-2023 15:18:33 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; httponly
      Date: Fri, 25 Aug 2023 15:18:32 GMT

         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

Below are the scopes I created on the app registration:

![image](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/assets/4291622/54ba06e1-513e-41a4-b0be-1b298582004e)

I feel that I am missing some configuration somewhere. Please help!

**Comment by WenningQiu** [comment]
Please hold off this issue. I realize that I probably should have read the README.md file first.

**Comment by WenningQiu** [comment]
It works after following procedures in Readme.md.
