### ISSUE TITLE
SignIn and SignOut links from AccountController not routable in Preview 3 of Razor Components project

### ISSUE THREAD

**Issue by khenzar** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#74]
### Describe the bug
Account controller from Microsoft.AspNetCore.Authentication.AzureAD.UI is not routable in Razor Components Preview 3.

### To Reproduce
Steps to reproduce the behavior (this is not to setup a working app with AzureAD authentication):
1. Using ASP.NET Core 3.0 SDK version 3.0.100-preview3-010431
2. Create new Razor Components project
3. Add reference to nuget package [Microsoft.AspNetCore.Authentication.AzureAD.UI](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.AzureAD.UI/3.0.0-preview3-19153-02) version 3.0.0-preview3-19153-02
4. Follow step 1 from tutorial [1-WebApp-OIDC\1-1-MyOrg](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-1-MyOrg) to register your application in AzureAD. 
5. Add following code to ConfigureServices() method of Startup class
```
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => configuration.Bind("AzureAd", options));
```
6. Modify appsettings.json with your app registration data as shown in step 2 of the mentioned tutorial
7. Put a link with 'href="/AzureAD/Account/SignIn"' in any of the *.razor component files, to simulate navigation.
8. Run the sample and try to navigate the SignIn link.
9. The navigation with fail with blank page and you will observe the following error in Output window in Visual Studio:
```
System.InvalidOperationException: 'Router' cannot find any component with a route for '/AzureAD/Account/SignIn', and no fallback is defined.
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh() ...
```

### Expected behavior
It should be possible to navigate to 'AzureAd/Account/SignIn' and 'AzureAd/Account/SignOut' from within Razor Components web application.

### Additional context
The sample was working correctly in Razor Components Preview 2 application.
The routing breaks after updating the sample to ASP.NET Core 3.0 Preview 3, especially replacing
```
app.UseRazorComponents<App.Startup>();
```
with
```
app.UseRouting(routes =>
{
  routes.MapRazorPages();
  routes.MapComponentHub<App>("app");
});
```
in Configure() method of Startup class.

It seems the new router only allows routes defined by Razor Components pages.
AccountController needs to be registered in the new routing pipeline.

**Comment by Valks** [comment]
Use the IUriHelper service, it has a Boolean forceLoad which will force the Razor Page to route to an external url instead of trying to handle it using blazor/razor components.

```
@inject IUriHelper UriHelper

<a onclick="@(() => UriHelper.NavigateTo("/AzureAd/Account/SignOut", true))">Sign Out</a>

```

**Comment by khenzar** [comment]
Hi Valks, thanks I have tried your suggestion.
Unfortunately, the same error persists.

I can confirm the UriHelper is used, as I have pulled out the onclick methods, so that I can put breakpoints in them:
```
private void NavigateSignIn() => UriHelper.NavigateTo(LinkSignIn, true);
private void NavigateSignOut() => UriHelper.NavigateTo(LinkSignOut, true);
```

The full exception that I see in VisualStudio, output from Debug:
```
System.InvalidOperationException: 'Router' cannot find any component with a route for '/AzureAD/Account/SignIn', and no fallback is defined.
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh()
   at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterCollection parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterCollection parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

**Comment by BlackFenix2** [comment]
I believe you have to also map the controllers in your routing endpoint builder. That is why the login/logout routes are not being found by your app. For anyone else experiencing this issue, see: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#migrate-mvc-controllers
