### ISSUE TITLE
Comparing aadAuthority Uri against host Authority

### ISSUE THREAD

**Issue by Valks** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#88]
```if(issuerValidators.ContainsKey(aadAuthority))```
Will always be false because aadAuthority is the full Uri path and not just the host. Assuming the issuer should be unique based on the full Uri path the Key should contain the full Uri path when calling: ```issuerValidators.Add(authority, issuerValidator);```

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/407932f4e5834fe6389ce7c0101cfefb0e53b65c/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs#L63

**Comment by deckerbd** [comment]
I'm running into the same thing. For my web app, I'm trying to use both OpenID and JwtBearer auth (our API and Web app/SPA are hosted together), and the logic ends up attempting to add the same key twice. In addition, it looks like these values don't match between OpenID and JwtBearer (see [Web](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/Microsoft.Identity.Web/StartupHelpers.cs#L41) vs [API](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/Microsoft.Identity.Web/WebApiStartupHelpers.cs#L33)) so changing just the `ContainsKey` lookup for the dictionary to use `aadAuthority` fails due to the extra slash.

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.Identity.Client.Extensions.Web.Resource.AadIssuerValidator.ForAadInstance(String aadAuthority) in C:\TFS2015\Git\SA-AzureADAuthenticationUtility\microsoft-authentication-extensions-for-dotnet\src\Microsoft.Identity.Client.Extensions.Web\Resource\AadIssuerValidator.cs:line 57
   at Microsoft.Identity.Client.Extensions.Web.ServiceCollectionExtensions.<>c__DisplayClass2_0.<AddProtectWebApiWithMicrosoftIdentityPlatformV2>b__1(JwtBearerOptions options) in C:\TFS2015\Git\SA-AzureADAuthenticationUtility\microsoft-authentication-extensions-for-dotnet\src\Microsoft.Identity.Client.Extensions.Web\ServiceCollectionExtensions.cs:line 198
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.CreateValue()
```

Not sure what would be the desired way of fixing this, I'm guessing just save the full authority? I can send a pull request if desired.

**Comment by jmprieur** [comment]
@deckerbd : yes please do.

**Comment by jmprieur** [comment]
@brentschmaltz @MarkZuber  FYI

**Comment by jmprieur** [comment]
fixed by @bgavrilMS in the Web API tutorial
came with https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/109
